#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <conio.h>

struct Node{
	char op;
	struct Node* next;
};

struct Node* head = NULL;

struct Node* createNewNode(char op){
	struct Node* newNode = (struct Node*)malloc(sizeof(struct Node));
	newNode->op = op;
	newNode->next = NULL;
	return newNode;
}

void PushOperator(char op){
	struct Node* newNode = createNewNode(op);
	newNode->next = head;
	head = newNode;
}

char PopOperator(){
	if(head == NULL) return ' ';
	struct Node* toDel = head;
	
	char returnOp = head->op;
	head = head->next;
	free(toDel);
	
	return returnOp;
}

int GetPriority(char op) {
    if(op == '^') return 3;
    if(op == '*' || op == '/') return 2;
    if(op == '+' || op == '-') return 1;
    return 0;
}

void InfixToPostfix(char inputString[], char newString[]){
	int j = 0;
    for (int i = 0; inputString[i] != '\0'; i++) {
        char token = inputString[i];
		
		//(A-Z, 0-9)
        if(isalnum(token)) newString[j++] = token;
        //Operator
		else{
            while(head != NULL && GetPriority(head->op) >= GetPriority(token)) {
                newString[j++] = PopOperator();
            }
            PushOperator(token);
        }
    }

    while(head != NULL){
        newString[j++] = PopOperator();
    }
    
    newString[j] = '\0';
}

void drawPatrick();

int main(){
	char infix[101], postfix[101];
	puts("Enter infix: ");
	scanf("%s", infix);
	
	InfixToPostfix(infix, postfix);
	
	puts("");
	puts("Postfix: ");
	printf("%s\n", postfix);
	
	puts("");
	puts("Ketik 1");
	while(1){
		char key = _getch();
		if(key == '1') break;
	}
	drawPatrick();
	return 0;
}

void drawPatrick(){
	puts("GGGGGGGGGGGGGGGGGGGGGGB#BBBBBBBB######BBBBBBBBGPPPPGGGGGGGGBBBGGPGGGGGGGGGGGGGGGGGGGGGGGGBBGPPPGGPPP");
	puts("GGGGGGGGGGGGGGGGGGBBBGGGGGGGGGGGB##BBBBBBB#BBBBBBBGGGGGBBBBGGPPPPGGGGGGGGGGGGGGGGGGGGGGGGGGPPPGGGGPP");
	puts("GGGGGGGGGGGGGGBBBBBBGPPGGGBGGGBBBGGPPPPPPPPPPGGGBBBBB#####BGGGGGGGGGGGGGGGGGGGGGGPPGBBGPPGGGGGGGGGGG");
	puts("GGGGGGGGGGGGBBBBGGGPGGGGBBBGP5PGGGGPGGGGGGGGGPPPPPPPPGGGBBBBBBBBBBBGGGGGGGGGGGGGBGPPGPPGGGGGGGGGBBB#");
	puts("GGGGGGGGGGBBBGGPPGGGGGGBBBBBBGPPGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPGBBB#BBBBBGGGGGBBBGPPPGGBBGGGGGB###BG");
	puts("GGGGGGGBBBGGPPGGGGGBBBGGGGGGGBGGBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGB####BBBB##BGGGBBBBBGGBB###BGPPP");
	puts("GGGBBBGGGPPPGGBGGGBBGPPGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBGGGGGB##BBBBBGGBBB###BGP5PPG");
	puts("GBBBGPPPGGGGGGGGBGGPPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBGGPPPPPPPPPPGB#########BGPP5PPGGG");
	puts("GPPGGGGGGGGGGGBBGPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB#BP555PGGGGPPPGGGGB###BBP55PPPGGGGGG");
	puts("GGGGGGGGGGGGGGGPPPPPGGGGGGGGGGGGGGGPPP55PPPGGGGGGGGGGGGGGGGGGGBGBBBGPPPPPPGGGGGBB###BGP55PPPGGGGGGGG");
	puts("GGGGGGGGGGGGGPPPPGGGGGGGGGGGGGGGGGP5J??7??JY5PGGGGGGGGGGGGGGGGPPPGGGGBBGGGGGGBB##BGPPPPPGGGGGGGGGGGG");
	puts("GGGGGGGGGGPPPGGPPPGGGGGGGGGGGGGGGP5?7!!!!!!7?Y5PPGGGGGGGGGGPPPPGGPPPPPPPGGBBB##BGP5PGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGPGGGGGGGGGPPPGGGGGGGGGPPY?7!!!!!!!!7?JYPPGGGGPPPPPGGGGPPPPPGGGB###BGPPPPGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPY?7!!!!!!!!!!7?Y5PPPPPPPGGGGGGPPPPGBB###GP5PPPPGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPY?7!!!!!!!!!!!!7?Y5PPPPPPGGGPGPGGBB##BGPPPPPGGGGPGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPY?7!!!!!!!!!!!!!!?YPGGGGGGGGGGGBB#BBPP5PPGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPY?7!!!!!!!!!!!!!!7YPPGB##BBBBB#BBGPPP5PGGGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGPGGGGGPY?7!!!!!!7????77?JYJ?JYPB&&##BGP55PPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGPPGGGPY?7!7??JYYJ???J5P5JJPGY?JG#BGP55PPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("PGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPGGPY?!7?5GG57~!JYYYYY5G&@#P??5PP55PGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPY?!!?5BG?^~5&&#GYJYP#@@#Y?JPGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBG");
	puts("GGGGGGGPGGGGGGGGGGGGGGGGGGGGGGPPPPY?!!!7JY?^:?B&@#PJ?JYPBPJ?5GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBBBBGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGPPGGGGGGPPP5Y7!!!!!?Y?^~YB&BP55Y??JJJ5GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBBBBGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGG5J7!!!!!7?JJ7?Y5P55YJJJJJYYYPPGGGGGGGGGGGGGGGGGGGGGGGGBBBBBBGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPY?7!!!!!!!7??JJJJJ?!!!!!7??YPGBBGGGGGGGGGGGGGGGGGGGBBBBBBBBGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPP5J7!!!!!!!!!!!!!!!!!!!!?J555YYJY5PPPGGGGGGGGGGGGGBBBBBBGGGGGGGGGGGGG");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGP5Y?7!!!!!!!!!!!!!!!!77?Y55Y?7!!!!7JYPPGGGGGGGGGBBBBGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGGPGGPPGGGGGGGGGGGGGGGGGP5J7!!!!!!!!!!!!!!!7JYYYJ?7!!!!!!!7?YPPGGGGGGBBBBGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGPPGGPPPGGGGGGGGGGGPPGGPPPY7!!!!!!!!!!!!!!?Y55?7!!!!!!!!!!!7JPGGGGGGGGBGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGPPPGGPGGGGGGGGGGGGGGGGGGGGBBBGY?777!!!!!!!!!!7?J?7!!!!!!!!!!!!!!?5PGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGG");
	puts("PPPPPGGGGGGGGGGGGGGGGGGGBBBBBGGG5Y?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7YPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");
	puts("PPPPPPGGGGGGPPPPPPGGGGBB#BGPPP5YYYJ7!!!!!77!!!!!!!!!!!!!!!!!!!777!7YPGP55PPGGGGGGGGGGGGGGGGGGGGGGPPP");
	puts("PPPPPPPGGGGGPPGGGGGGBB#BGGPPP5?^~7?7!!!!777!!!!!!!!!!!!!!!!!!?Y5J??YP5J??JYPGGGGGGGGGGGGGGGGGGGGGPPG");
	puts("PPPGGGGPGGGGPPGGBBBBBBPPPPGGG57::!77777???77!!!!!!!!!!!!!!~!7JYJYYYJJJ?77?Y5GGGGGGGGGGGGGGGGGGGGGGGG");
	puts("GGGGGGGPGGGGGGB##BBGPPPPGGGGGP?^.^!7777?YYJ????777777777!!!?JYJJPBGYJJJJJ55PGGGGGGGGGGGGGGGGGGGGGGB#");
	puts("GGGGGGGGGGBB##BBGPPPGGGGGGGGGG57:..^^^^:^^^^^~!!!7????????JPB##B#&#GGPPPPPGGGGGGGGGGGGGGGGGGGGGGBB#B");
	puts("GGGGGGGGBB#BBGP5PPGGGGGGGGGGGGG5?^.  ...... ...::^^^^^:::~JG&&#BBBBGGGGGGGGGGGGGGGGGGGGGGGGGGBB#BGP5");
	puts("GGGGGBBBBBGPPPPGGGGGGGGGGGGGGGGGPY7^:.     .:^~!!!!77!^:^!?JYY55PGGGGGGGGGGGGGGGGGGGGGGGGGGBB#BGP55P");
	puts("GGGBB#BGPPPPGGGGGGGGGGGGGGGGGGGGGGPY?7~^:.:^!77!!!!7777777!~7YPPGGGGGGGGGGGGGGGGGGGGGGGGGB#BBP55PPPP");
	puts("B##BGGPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGPPP5YJJJJ?7!!!!!!!777?J5PGGGGGGGGGGGGGGGGGGGGGGGGGGBBBGP55PPPPPP");
	puts("#BGPPPGGGGGGGGGGGGGGGGGGGGGGGPGGGGGGPGGGGGGP5YYJ?777!!!!7?Y5GGGGGGGGGGGGGGGGGGGGGGGGBB#BGP55PPPPPPPP");
	puts("PPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGP55YJJJJJJ5PPGGGGGGGGGGGGGGGGGGGGGB##BG555PPPPPPPPPP");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPGGGGGGGGGGGGGGGGGGGGBB##BP55PPPPPPPPPPPPP");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB##BG555PPPPPPPPPPPPPP");
	puts("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB#BGP55PPPPPPPPPPPPPPPPP");
	puts("GGGGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB##BGP55PPPPPPPPPPPPPP55PPP");
	puts("GGGGGGGGGGGGGGPPPPGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB##BP55PPPPPPPPPP55PPPP555PPP");
}
